# Generated by Django 4.1.7 on 2023-02-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_generations', models.IntegerField()),
                ('max_population', models.IntegerField()),
                ('village_name', models.CharField(max_length=55)),
                ('gridLength', models.IntegerField()),
                ('seed', models.CharField(max_length=75000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontcapapi.village')),
            ],
        ),
    ]
