# Generated by Django 4.1.7 on 2023-02-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontcapapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highscore',
            old_name='village_id',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='user_id',
            new_name='user',
        ),
    ]
