# Generated by Django 4.1.7 on 2023-02-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontcapapi', '0002_rename_village_id_highscore_village_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='gridLength',
            new_name='grid_length',
        ),
        migrations.AlterField(
            model_name='village',
            name='max_generations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='max_population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='seed',
            field=models.CharField(max_length=75000, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_name',
            field=models.CharField(default='Unloved Village', max_length=55),
        ),
    ]
