# Generated by Django 4.1.7 on 2023-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontcapapi', '0003_rename_gridlength_village_grid_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='seed',
            field=models.JSONField(max_length=75000, null=True),
        ),
    ]
